name: 💅 Lint
run-name: Lint run
on: [push]
jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v2
      - name: Set up Bun
        uses: oven-sh/setup-bun@v1

      - name: Install Dependencies
        run: bun install

      - name: Code Linting
        run: bun run lint
